### ISSUE TITLE
Access glottolog data from github repository clone or fork

### ISSUE THREAD

**Issue by xrotwang** [ropensci/lingtypology#1]
Hi there,
great work!
I've seen [here](https://cran.rstudio.com/web/packages/lingtypology/vignettes/lingtypology.html) that you changed some of the glottolog data before making it accessible via your package. I think the best approach to do this would be as follows:
- Access glottolog data in the format it is curated in, see https://github.com/clld/glottolog
- Base your package on a fork of https://github.com/clld/glottolog which adds your changes.

Alternatively, your package could access the glottolog data locally - i.e. in a local copy of clld/glottolog on the users machine. I don't know how this would work in terms of performance. But it would give your users the maximum in terms of freedom, because they could use the functionality of your package on their own forks of glottolog.

**Comment by agricolamz** [comment]
Hi Robert,
I'm really glad to see your issue.

Unfortunately, I can't do it the way you propose, because in clld repository it stored in different tables. It is easier for me to work with one table. But I clearly understood that
1) I should mark the version of glottolog I use. You make updates, so everybody should know how old are my data. I'll work on it little bit later.
2) I should give users an ability to work with true glottolog data without my (nasty?) corrections. I'll try to do it tomorrow.
3) I should propose you my corrections. Some of them (I hope) are not so useless (for example Silesian and Slavomolisano)… Some day in January, I'll write you about it.

I think, that it is possible to close this issue doing 2) and 1). Are you agree?

**Comment by xrotwang** [comment]
Yes, the issue can be closed. I'll have a look at your R code when I find time to see whether the creation of the RData object could be easily factored out. Alternatively, I may add functionality to pyglottolog to create the RData object from python using [rpy2](http://rpy2.bitbucket.org/).

**Comment by xrotwang** [comment]
Actually, I'm not much of a R person, but could you give me the specification of the single table you need from glottolog? Writing this data to a csv file shouldn't be much of a problem from pyglottolog.

**Comment by agricolamz** [comment]
Here is a link to the csv version. https://goo.gl/qwIDlS

It would be wonderful, if it will be an ability to produce something similar. Unfortunately I'm not much of a Python person.

**Comment by xrotwang** [comment]
@agricolamz Thanks! Creating csv like this from pyglottolog should be pretty simple. So If lingtypology could read its data from a file like this, it would be possible for anyone with a (possibly modified) clone of `clld/glottolog` to just run a `pyglottolog` command to create the csv including local modifications.

**Comment by agricolamz** [comment]
@xrotwang I can't find any tutorial for pyglottolog. Am I a such bad googler?

**Comment by xrotwang** [comment]
Sorry, pyglottolog isn't documented well so far. We just moved to curating the data in this new way recently. But what I would propose is the following:
- I create csv like the one you linked to, and document how this can be done from any fork of the clld/glottolog repos.
- You could adapt lingtypology to read the glottolog data from such a csv file.

Sounds good?

**Comment by agricolamz** [comment]
It will be great, Robert!
