### ISSUE TITLE
Unable to view a language on a map

### ISSUE THREAD

**Issue by LacinaSilue** [ropensci/lingtypology#46]
Dear all,

I am Silué, a PhD student in linguistics in France. I have discovered lingtypology very recently and I am a very new user. I would like to ask for some help related to an issue I am facing with lingtypology. In fact, I am studying a language called **Kafire**. It is part of Senufo languages and I wanted to be able to view that language on a map. However, it does not appear while I know that it is on Glottolog with the code **Kafire 1243**. For instance, a colleague of mine wanted to create a map with the languages that have logophoricity in the project Reported Speech in African Storytelling, but it is only Cebaara Senufo that could appear in place and instead of Kafire.  I do not know if this issue is related to the fact that Kafire does not have an ISO code. Moreover, I do not understand why it is, like other Senufo varieties (Kufuru, Tagara...) a child of **Cebaara Senufo** in Glottolog while we know that all of them are the varieties of Senanri (Central Senufo). So, they should be sisters. Could someone help me?

Please, put the results of these functions below, if your issue is related to the technical bugs. Thank you!

<details> <summary> info about OS and package versions </summary>
```
sessionInfo()$R.version$platform
sessionInfo()$R.version$version.string
packageVersion("leaflet")
packageVersion("lingtypology")
```
</details>

**Comment by agricolamz** [comment]
Dear Silué,

I think you mentioned two problems:

* you are not happy with genealogical affiliation of Kafite in glottolog database;
* there is no coordinates for Kafire in `lingtypology`.

I think both are not the problem of the `lingtypology` package. First issue should be addressed to [glottolog repository](https://github.com/glottolog/glottolog), providing some references. They answer fast, and if they are agree with you, they will add changes to the next version of glottolog database.

Second is also the problem of glottolog database itself, since there is no any coordinates associated with [Kafire](https://glottolog.org/resource/languoid/id/kafi1243) in glottolog database.  As a result, some languages/lects are discriminated (12 367 of 20 742, around 60%) and can't be mapped in the easy way with the following code:

```
> map.feature("Kafire")
Warning message:
There is no coordinates for languages Kafire 
```

But there is no reason for losing heart --- it is possible to create a map, providing latitude and longitude values (I provided just random one, since I don't know anything about this language):

```
map.feature("Kafire", 
            latitude = 9.416667,
            longitude = -5.616667)
```
![image](https://user-images.githubusercontent.com/15956515/81365522-04c8ad80-90f1-11ea-95df-72a6576c9e16.png)

**Comment by LacinaSilue** [comment]
Dear agricolamz,

Thanks for your response. It is clear now. So, from what I understand with your comment, there should be a preliminary step to make with glottolog where I should deal with the matter of affiliation and also the coordinates of the language. Thanks. But, regarding your solution with adding coordinates manually, how does it work if I have to add several coordinates (of the three big villages where the language is spoken) ? Or maybe I do not understand well the notion of "coordinates of the language " here. Thanks. If not, these are the coordinates of the places where Kafire is spoken :

**Sirasso** 

latitude: 9.276686
longitude: -6.098986

**Nafoun** 

latitude: 9.334722
longitude: -6.211667

**Kanoroba**

latitude: 9.110875
longitude: -6.122378

**Comment by agricolamz** [comment]
You can put a vector there, for example:

```
map.feature(language = c("Kafire", "Kafire", "Kafire", "Goo"), 
            features = c("Atlantic-Congo", "Atlantic-Congo", "Atlantic-Congo", "Mande"),
            latitude = c(9.276686, 9.334722, 9.110875, 7.580998),
            longitude = c(-6.098986, -6.211667, -6.122378, -7.562563))
```

![image](https://user-images.githubusercontent.com/15956515/81391261-77ec1700-9125-11ea-83cb-22312df1ea62.png)

**Comment by LacinaSilue** [comment]
> You can put a vector there, for example:
> 
> ```
> map.feature(language = c("Kafire", "Kafire", "Kafire", "Goo"), 
>             features = c("Atlantic-Congo", "Atlantic-Congo", "Atlantic-Congo", "Mande"),
>             latitude = c(9.276686, 9.334722, 9.110875, 7.580998),
>             longitude = c(-6.098986, -6.211667, -6.122378, -7.562563))
> ```
> 
> ![image](https://user-images.githubusercontent.com/15956515/81391261-77ec1700-9125-11ea-83cb-22312df1ea62.png)

Now I will deal with the other issues with Glottolog as suggested by you. Thanks a lot.

**Comment by LacinaSilue** [comment]
It works !!! Now I will deal with the other issues with Glottolog as suggested by you. Thanks a lot.

**Comment by SimonGreenhill** [comment]
(Glottolog will also be interested in the locations too)

**Comment by LacinaSilue** [comment]
> (Glottolog will also be interested in the locations too)

Understood. Thanks.
